export const countries = [
  { value: 'AF', label: 'Afghanistan', code: '^\\d{4}$', example: '1001' },
  { value: 'DZ', label: 'Algeria', code: '^\\d{5}$', example: '16000' },
  { value: 'AR', label: 'Argentina', code: '^[A-Z]?\\d{4}[A-Z]{3}$', example: 'C1000AAO' },
  { value: 'AU', label: 'Australia', code: '^\\d{4}$', example: '2000' },
  { value: 'AT', label: 'Austria', code: '^\\d{4}$', example: '1010' },
  { value: 'AZ', label: 'Azerbaijan', code: '^AZ\\d{4}$', example: 'AZ1000' },
  { value: 'BD', label: 'Bangladesh', code: '^\\d{4}$', example: '1000' },
  { value: 'BY', label: 'Belarus', code: '^\\d{6}$', example: '123456' },
  { value: 'BE', label: 'Belgium', code: '^\\d{4}$', example: '1000' },
  { value: 'BR', label: 'Brazil', code: '^\\d{5}-\\d{3}$', example: '12345-678' },
  { value: 'BG', label: 'Bulgaria', code: '^\\d{4}$', example: '1000' },
  { value: 'CA', label: 'Canada', code: '^[A-Za-z]\\d[A-Za-z]\\s?\\d[A-Za-z]\\d$', example: 'A1B 2C3' },
  { value: 'CN', label: 'China', code: '^\\d{6}$', example: '100000' },
  { value: 'CO', label: 'Colombia', code: '^\\d{6}$', example: '110111' },
  { value: 'CU', label: 'Cuba', code: '^\\d{5}$', example: '10100' },
  { value: 'CY', label: 'Cyprus', code: '^\\d{4}$', example: '1010' },
  { value: 'CZ', label: 'Czechia', code: '^\\d{3}\\s?\\d{2}$', example: '110 00' },
  { value: 'DK', label: 'Denmark', code: '^\\d{4}$', example: '1000' },
  { value: 'DO', label: 'Dominican Republic', code: '^\\d{5}$', example: '10101' },
  { value: 'FI', label: 'Finland', code: '^\\d{5}$', example: '00100' },
  { value: 'FR', label: 'France', code: '^\\d{5}$', example: '75001' },
  { value: 'GE', label: 'Georgia', code: '^\\d{4}$', example: '0101' },
  { value: 'DE', label: 'Germany', code: '^\\d{5}$', example: '10115' },
  { value: 'GR', label: 'Greece', code: '^\\d{3}\\s?\\d{2}$', example: '101 88' },
  { value: 'HU', label: 'Hungary', code: '^\\d{4}$', example: '1011' },
  { value: 'IN', label: 'India', code: '^\\d{6}$', example: '110001' },
  { value: 'ID', label: 'Indonesia', code: '^\\d{5}$', example: '10110' },
  { value: 'IE', label: 'Ireland', code: '^[A-Za-z0-9]{3}\\s?[A-Za-z0-9]{4}$', example: 'D01 F5X2' },
  { value: 'IL', label: 'Israel', code: '^\\d{7}$', example: '1234567' },
  { value: 'IT', label: 'Italy', code: '^\\d{5}$', example: '00100' },
  { value: 'JP', label: 'Japan', code: '^\\d{3}-\\d{4}$', example: '123-4567' },
  { value: 'KZ', label: 'Kazakhstan', code: '^\\d{6}$', example: '123456' },
  { value: 'MA', label: 'Morocco', code: '^\\d{5}$', example: '10000' },
  { value: 'NL', label: 'Netherlands', code: '^\\d{4}[ ]?[A-Za-z]{2}$', example: '1234 AB' },
  { value: 'NZ', label: 'New Zealand', code: '^\\d{4}$', example: '1010' },
  { value: 'NO', label: 'Norway', code: '^\\d{4}$', example: '1234' },
  { value: 'PL', label: 'Poland', code: '^\\d{2}-\\d{3}$', example: '02-401' },
  { value: 'QA', label: 'Qatar', code: '^\\d{5}$', example: '12345' },
  { value: 'RU', label: 'Russia', code: '^\\d{6}$', example: '102046' },
  { value: 'SA', label: 'Saudi Arabia', code: '^\\d{5}$', example: '12141' },
  { value: 'RS', label: 'Serbia', code: '^\\d{5}$', example: '11000' },
  { value: 'ES', label: 'Spain', code: '^\\d{5}$', example: '28001' },
  { value: 'SE', label: 'Sweden', code: '^\\d{3}[ ]?\\d{2}$', example: '123 45' },
  { value: 'CH', label: 'Switzerland', code: '^\\d{4}$', example: '8001' },
  { value: 'TH', label: 'Thailand', code: '^\\d{5}$', example: '10100' },
  { value: 'TR', label: 'Turkey', code: '^\\d{5}$', example: '34000' },
  { value: 'UA', label: 'Ukraine', code: '^\\d{5}$', example: '01001' },
  { value: 'AE', label: 'United Arab Emirates', code: '^\\d{5}$', example: '12345' },
  { value: 'GB', label: 'United Kingdom', code: '^[A-Z]{1,2}[0-9][A-Z0-9]?\\s?[0-9][A-Z]{2}$', example: 'SW1A 0AA' },
  { value: 'US', label: 'United States', code: '^\\d{5}(-\\d{4})?$', example: '12345 or 12345-6789' },
  { value: 'UZ', label: 'Uzbekistan', code: '^\\d{6}$', example: '100000' },
]